### ISSUE TITLE
Question/Request: Scenarios or Roles

### ISSUE THREAD

**Issue by tinydogio-joshua** [devcontainers/spec#100]
Hello,

This may be covered already but thought I'd throw it out here just in case.

Has there been any discussion or plans around allowing logic within the devcontainer spec allowing for different scenarios or role based settings/setups? For instance, it would be nice for a team in a monorepo to be able to switch their devcontainer config based on the task at hand (IE: Frontend dev integrating with services, QA testing out the full stack, Backend dev only working on an API, etc).

I could imagine the IDE detecting these options when loading the devcontainer.json file and prompting the user to select the scenario/role they want to load.

Thank you for your time. 🙏

**Comment by jkeech** [comment]
This is currently supported by having multiple `devcontainer.json` files in your repo with the following structure:

```
/.devcontainer/role1/devcontainer.json
/.devcontainer/role2/devcontainer.json
```

When you create the dev environment, you can select the appropriate devcontainer config for your role/team/etc.

As an example, in GitHub Codespaces, if you have multiple devcontainers defined as described above, it will prompt you to select one when creating a codespace for that repo.

**Comment by jkeech** [comment]
The spot in the spec which describes that is https://github.com/devcontainers/spec/blob/main/docs/specs/devcontainer-reference.md#devcontainerjson. 

>.devcontainer/devcontainer.json
.devcontainer.json
.devcontainer/**/devcontainer.json (where ** is a sub-folder)
>
>It is valid that these files may exist in more than one location, so consider providing a mechanism for users to select one when appropriate.

**Comment by tinydogio-joshua** [comment]
That's fantastic. Thank you for pointing me there. 🙏

**Comment by tinydogio-joshua** [comment]
I'll go ahead and close this since you've answered my question. Thank you again. 🙏
