### ISSUE TITLE
Allow port forwarding for multi container (composer) setups

### ISSUE THREAD

**Issue by aheissenberger** [devcontainers/spec#112]
Currently only port from the main service container are possible to forward. 
The only workaround is to have all containers on the same network and insure that all containers have different ports which breaks some setups of micro services all using the same http port for their api.

Allow to forward any port from any service.

**Comment by Chuxel** [comment]
@aheissenberger The spec allows `"host:port"` forwarding and the VS Code Remote - Contaienrs / Dev Containers extension for VS Code implements it. Right now Codespaces has not implemented this - is that where you are running into this problem?  Or are you looking for something else?  

If its Codespaces specific, this is likely a dupe of https://github.com/community/community/discussions/9420

**Comment by aheissenberger** [comment]
oh - you are absolute righ!

But this is really not easy to find and it breaks if the there is a none allowed character in the host name - e.g. `service_b` the `_` is not an allowed character in a hostname, but a valid character in a docker compose file for a service name :-(.

I get a validation error when adding this to my `devcontainer.json` but with the misleading message about integer values:
![error msg](https://uc9ef02de1b6ed9c65bedf466a8c.dl.dropboxusercontent.com/cd/0/inline/Buxu6yovMr5SmT-gTSRXAEKTJPUPD2r1PSvX63arBJuFTz4mA-zHNcNVQEjNGq6OT6lZsF5PQv4A2g61k3Lm1rtcl1chyETnMDkovuHOLEMxbDgULZGZHbOS3TsGnQ23_a8-9OkUsczpzsumiZmV-GY5VA7CYOnY2kYq9bBS0fV81Q/file#)
