### ISSUE TITLE
Publish devcontainer.json schema

### ISSUE THREAD

**Issue by chrmarti** [devcontainers/spec#14]
Currently hosted in the VS Code repo, the source should move to the reference implementation when that becomes available.

Similarly to the tsconfig.json schema, we could submit a PR to https://github.com/SchemaStore/schemastore to make it available at schemastore.org.

**Comment by greggroth** [comment]
Is this referring to the JSON Schema doc in https://github.com/microsoft/vscode/tree/main/extensions/configuration-editing/schemas?  Perhaps related to https://github.com/microsoft/dev-container-spec/issues/1, it would be handy if that schema didn't include [VS Code references](https://github.com/microsoft/vscode/blob/d2db6fb2d07596b025d3405085c9ad2ac7670ef6/extensions/configuration-editing/schemas/devContainer.schema.generated.json#L124) that schema from being used to strictly verify a devcontainer.json file.  There are also properties like [`allowComments` and `allowTrailingCommas`](https://github.com/microsoft/vscode/blob/d2db6fb2d07596b025d3405085c9ad2ac7670ef6/extensions/configuration-editing/schemas/devContainer.schema.generated.json#L4-L5) that aren't part of the JSON Schema spec. Are those something VS Code supports as an extension to the spec?

**Comment by Chuxel** [comment]
@greggroth Yeah the devcontainer.json file is "json5 / jsonc / json with comments" which is an extension of the base json format. I'm not aware of an official way to denote that in a json schema.  That particular copy is the one used in production by VS Code and Codespaces today, which also predates the refactoring being discussed here.  The ref is for a property that would move with #1 (specifically, that's VS Code settings which has a schema of its own).

I do think it would be reasonable, however to allow people to submit PRs to the spec's copy of the schema that would be located here that would include refs to an externally defined tool/service specific schema not maintained in this repository.  e.g. `customizations.vscode` points to one thing, `customizations.jetbrains` another,  `customizations.codespaces`, `customizations.gitpod`, another, etc.

@chrmarti was this how you were thinking about getting the schema in shape for the spec?

**Comment by chrmarti** [comment]
> I do think it would be reasonable, however to allow people to submit PRs to the spec's copy of the schema that would be located here that would include refs to an externally defined tool/service specific schema not maintained in this repository. e.g. `customizations.vscode` points to one thing, `customizations.jetbrains` another, `customizations.codespaces` another, `customizations.gitpod` another, etc. That would allow for better validation than just marking these as `any`.
> 
> @chrmarti was this how you were thinking about getting the schema in shape for the spec?

Correct.

@aeschli Could you advise if this makes sense: We would like to publish the devcontainer.json schema at schemastore.org (like TypeScript for tsconfig.json does) and have it reference other tools-specific parts using `"$ref"`. The goal is to have a tools-independent schema that references tools-specific schema parts and make all that available to other tools/editors. E.g., VS Code would then just reference the devcontainer.json schema on schemastore.org (like it does for the tsconfig.json schema).

**Comment by aeschli** [comment]
The problem of the $ref would be that the base schema would have to know all possible extensions. That's not very practical.

In VS Code we allow that a file or file extension can be associated with multiple schemas. These are independent schemas each describing a seperate part of the JSON structure. The schmeas are not referencing each other. The schema service in the editor combines all of these with 'allOf'.
So it will be the editors job to bring the various schemas together. In VS Code, schema associations can done with user settings or by extensions. E.g. the codespace extension would associate its schema for the codespace specific parts of devcontainer.json.

**Comment by chrmarti** [comment]
Makes sense. One disadvantage might be that other editors will not offer IntelliSense for the VS Code and Codespaces parts, but that might be fine.

**Comment by aeschli** [comment]
I suggest the following structure for the schema:

| Document name         | Purpose     | Hosted on |
|--------------|-----------|------------|
| devContainer.schema.json | master schema consisting only of references to the schemas below (base schema as well as all schemas containing vendor specific properties) | github.com/devcontainers/spec |
| devContainer.base.schema.json | schema describing all base properties as documented [here](https://github.com/devcontainers/spec/blob/main/docs/specs/devcontainerjson-reference.md) | github.com/devcontainers/spec |
| devContainer.vscode.schema.json | schema describing vscode specific properties | github.com/Microsoft/vscode |
| devContainer.codespaces.schema.json | schema describing codespaces specific properties | github.com/github/codespaces or similar |
| devContainer.vendorFoo.schema.json | schema describing 'vendor foo' specific properties | location provided by 'vendor foo' |


- The [catalog file at schemastore.org](https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json) will get an entry to the master schema:
```json
    {
      "name": "Dev Container configuration file",
      "description": "The devcontainer.json file contains any needed metadata and settings required to configurate a development container for a given well-defined tool and runtime stack",
      "fileMatch": ["devcontainer.json", ".devcontainer.json"],
      "url": "https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.schema.json"
    }
```
- Vendors such as VS Code, Codespace, GitPod, Foo.. are free to choose any hosting location (can also be on schemastore.org)
- The master schema is just a collection of $refs that are and'ed: `allOf: [ { $ref: devContainer.base.json, $ref: ..., $ref .... } ]`.
- For a new vendor to add a new $ref to the master schema, a PR against  devcontainers/spec/ needs to be made. We will need to come up with a policy that decides which contributions can be accepted.

I imagine the policy to accept a new $ref would be:
- the newly added properties need to follow certain naming guidelines (camelCase, dot separated, ect...)
- all properties need to be documented
- a global link to documentation/spec needs to be provided so it can be added to the devcontainers/spec documentation as well

**Comment by bamurtaugh** [comment]
Assigning to myself to update our documentation (containers.dev).
