### ISSUE TITLE
Descriptions for `build.cacheFrom` has irrelevant lines

### ISSUE THREAD

**Issue by sarisia** [devcontainers/spec#154]
https://github.com/devcontainers/spec/blob/67d2817a47ba550e757913c8a8885d78147bf13e/docs/specs/devcontainerjson-reference.md?plain=1#L45

I think these lines are not applied to `build.cacheFrom`:

> Note that the array syntax will execute the command without a shell. You can [learn more](https://containers.dev/implementors/json_reference/#formatting-string-vs-array-properties) about formatting string vs array properties.

**Comment by samruddhikhandale** [comment]
> cc @samruddhikhandale any thoughts? I thought they'd apply, but I may be mistaken.

Yep, looks good to me as well.

**Comment by samruddhikhandale** [comment]
Ah, I think I misread the question the first time.

> Note that the array syntax will execute the command without a shell. You can [learn more](https://containers.dev/implementors/json_reference/#formatting-string-vs-array-properties) about formatting string vs array properties.

Yep, doesn't make sense for this `build.cacheFrom` option, I'll remove it.

**Comment by samruddhikhandale** [comment]
Opened PRs 

- https://github.com/devcontainers/spec/pull/190
- https://github.com/devcontainers/devcontainers.github.io/pull/142

**Comment by samruddhikhandale** [comment]
Closing as completed!
