### ISSUE TITLE
Use devcontainer.json in subdirectories in monorepo

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/spec#159]
We may want to work with different Dev Containers for each subdirectory. (e.g., a monorepo like https://github.com/apache/arrow)
In such a case, VSCode can recognize any `devcontainer.json` by opening a subdirectory, but Codespaces only recognizes those in the root directory.

I am wondering if it is possible to put a new type configuration file (such as `.devcontainer-paths.json`?) in the root directory with the paths to each `devcontainer.json` so that the tool is aware of each container definition.

**Comment by samruddhikhandale** [comment]
Codespaces supports monorepo and multi-repo scenarios. Have you taken a look at this [blog post](https://github.blog/2022-04-20-codespaces-multi-repository-monorepo-scenarios/#:~:text=We%20heard%20you%20loud%20and%20clear%20and%20are,long%20as%20they%20follow%20the%20pattern%20of.devcontainer%2F%24%20%7BDIR%7D%2Fdevcontainer.json) ?

If yes, then are you looking forward to another specification for mono repo? would like to clarify my understanding.

**Comment by Chuxel** [comment]
@samruddhikhandale - I think the ask here is not to have to put everything under `.devcontainer` which is at the root. ("but Codespaces only recognizes those in the root directory" being the notable piece). 

Instead the request is to allow a `.devcontainer` folder or `.devcontainer.json` file to be in any sub-folder.

The VS Code Dev Containers extension is behind on implementing everything under `.devcontainer` at the root, but this is different.

**Comment by eitsupi** [comment]
> Codespaces supports monorepo and multi-repo scenarios. Have you taken a look at this [blog post](https://github.blog/2022-04-20-codespaces-multi-repository-monorepo-scenarios/#:~:text=We%20heard%20you%20loud%20and%20clear%20and%20are,long%20as%20they%20follow%20the%20pattern%20of.devcontainer%2F%24%20%7BDIR%7D%2Fdevcontainer.json) ?

Thanks for pointing this out.
Sorry, I wasn't aware that this structure was defined in the spec!

https://github.com/devcontainers/spec/blob/9552d0ff1017d750ca94d5fa95e0af060e5c03bd/docs/specs/devcontainer-reference.md?plain=1#L19-L21

After trying it out, I think this behavior of Codespaces is sufficiently attractive.

But VSCode Dev Container doesn't seem to recognize `.devcontainer/**/devcontainer.json`, so I guess we need to place `.devcontainer.json` in a subdirectory like `**/` for now and create a container from that directory?
It would be great if VSCode DevContainer supported `.devcontainer/**/devcontainer.json` and users can choose these.
Should I create an issue on https://github.com/microsoft/vscode-remote-release?

**Comment by Chuxel** [comment]
> It would be great if VSCode DevContainer supported .devcontainer/**/devcontainer.json and users can choose these.
Should I create an issue on https://github.com/microsoft/vscode-remote-release?

@chrmarti Raise https://github.com/microsoft/vscode-remote-release/issues/7548 but there's not much of a description, so can add that.  You can upvote there!

**Comment by Chuxel** [comment]
@eitsupi Would you like to keep this open for using any sub-folder or do you think we should close as a dupe of getting this into the Dev Containers extension (https://github.com/microsoft/vscode-remote-release/issues/7548)?

**Comment by eitsupi** [comment]
Closing in favor of `.devcontainer/**/devcontainer.json` pattern.
Thanks.
