### ISSUE TITLE
devcontainer-features.json's mounts property?

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/spec#173]
It does not look like it is included in the document.

https://github.com/devcontainers/spec/blob/7791da141b7996865d88ddd977ef2ca9b8ad932c/schemas/devContainerFeature.schema.json#L62-L66

https://github.com/devcontainers/spec/blob/7791da141b7996865d88ddd977ef2ca9b8ad932c/docs/specs/devcontainer-features.md?plain=1#L30-L49

**Comment by samruddhikhandale** [comment]
> It does not look like it is included in the document

Good catch. Thanks for reporting.

**Comment by samruddhikhandale** [comment]
Opened PRs for the doc update -

- https://github.com/devcontainers/spec/pull/177
- https://github.com/devcontainers/devcontainers.github.io/pull/134

**Comment by samruddhikhandale** [comment]
Closing as completed!
