### ISSUE TITLE
`docs/specs/devcontainer-features.md` is not synced to containers.dev

### ISSUE THREAD

**Issue by sarisia** [devcontainers/spec#174]
e.g. `docs/specs/devcontainer-features.md` has the word `(omitting a version tag)` in `installAfter` description, but https://containers.dev/implementors/features/ does not.

https://github.com/devcontainers/spec/blob/7791da141b7996865d88ddd977ef2ca9b8ad932c/docs/specs/devcontainer-features.md?plain=1#L47

**Comment by samruddhikhandale** [comment]
Thanks for reporting!

**Comment by samruddhikhandale** [comment]
PR with the update - https://github.com/devcontainers/devcontainers.github.io/pull/132

**Comment by samruddhikhandale** [comment]
Closing as completed!
