### ISSUE TITLE
`overrideFeatureInstallOrder` is missing in `schema.json`

### ISSUE THREAD

**Issue by sarisia** [devcontainers/spec#175]
[`overrideFeatureInstallOrder`](https://containers.dev/implementors/json_reference/#general-properties) is available in docs but is missing in https://github.com/devcontainers/spec/blob/main/schemas/devContainer.base.schema.json and VSCode complains about it:

![image](https://user-images.githubusercontent.com/33576079/211880063-2e18c7fe-ddd1-4039-b8ba-9123dca01de0.png)

**Comment by samruddhikhandale** [comment]
Thanks! 
Created a PR to update the schema - https://github.com/devcontainers/spec/pull/176

**Comment by chrmarti** [comment]
Should be fixed with https://github.com/devcontainers/spec/issues/93 (will be in the next VS Code Insiders and Stable releases).

**Comment by samruddhikhandale** [comment]
Closing as completed! 

![image](https://user-images.githubusercontent.com/24955913/217043777-6f95df97-6935-464b-b3e0-d700812dc5d0.png)
