### ISSUE TITLE
[proposal] Feature Vendoring

### ISSUE THREAD

**Issue by l0rem1psum** [devcontainers/spec#199]
In situations where an internet connection is absent, it will be helpful to download features in advance and later unpack and use it.

For instance, by using `devcontainer features vendor [--vendor-dir]` command, features will get downloaded and vendored into .devcontainer/.vendor. Later on a PC with no internet connection, the devcontainer implementation will attempt to read from .devcontainer/.vendor directory for vendored features.

Maybe the spec can define a standard vendoring path + vendor directory indexing file (e.g. `.devcontainer/.vendor/vendor.json`).

**Comment by l0rem1psum** [comment]
I have also submitted an issue here: https://github.com/devcontainers/cli/issues/399 because I wasn't sure if this is better proposed as a devcontainer spec or as an implementation feature.

**Comment by joshspicer** [comment]
Thanks for the proposal.  To keep to conversation history cleaner, i'll close this issue and keep open your issue on the CLI (this seems like something that makes sense as a Feature of the CLI).  Feel free to reopen if you disagree.
