### ISSUE TITLE
Private Template Distribution & Local Testing

### ISSUE THREAD

**Issue by minasouliman** [devcontainers/spec#212]
I had a quick question regarding the devcontainer template spec. I see that we can use any OCI-compliant registry to host/distribute our templates, but I couldn't find any references to, or examples of, how to enable someone else to get access to these hosted templates without simply adding them to the global index that's referenced in the starter templates. 

My use case is that I'd like to be able to create templates for our dev team but unfortunately we're not able to make those templates public given that they use a number of proprietary libraries that are internally-hosted. The perfect situation would be being able to host the templates in an Azure Container Registry and then enable someone to add that registry to a local index that is appended to the global one on github. Is that mechanism in place or at all being discussed as part of the spec? 

Second question -- Is there any way of locally testing the template before shipping it? I'm primarily interested in testing the user choice menu and making sure that the references to those choices in devcontainer.json are correct.

Apologies if this is not in the right place, just let me know and I can move it to the appropriate repo 🙂

**Comment by joshspicer** [comment]
Hey! Is is _not_ a requirement to "register" your Features/Templates with our index in order for others to use them in their dev containers.  The index is simply to aid in discovery.  As long as the published Features are marked as 'public' in your registry, you should be able to reference them in a dev container (they _won't_ however show up in our VS Code extension, but that's fine).

If they're private (as you're asking), the dev container CLI [attempts to look for credential in several different places](https://github.com/devcontainers/cli/blob/main/src/spec-configuration/httpOCIRegistry.ts#L125-L169). For example, if they are private Features in GHCR and you're using Codespaces, you can grant the included `GITHUB_TOKEN` access to [read those private packages](https://docs.github.com/en/enterprise-cloud@latest/codespaces/managing-your-codespaces/managing-repository-access-for-your-codespaces).  I also have a [PR open](https://github.com/devcontainers/cli/pull/444) to enhance the experience of using pushing/pulling Features/Templates in a private AzureCR.

If you're specifically looking for an index-like experience for private Features/Templates - that's something on our radar but not currently planned work. There's a [discussion open](https://github.com/devcontainers/spec/discussions/136) on that if you'd like to share your thoughts :).   When publishing, our tooling always publishes an extra package that we call the 'metadata package' [(eg)](https://github.com/devcontainers/templates/pkgs/container/templates).  We use this to build the index - it might be helpful if you wanted to wire something simple up.

**Comment by joshspicer** [comment]
For question (2), in order to test your Template i'd suggest using that `devcontainer templates apply` command with various inputs. You can also see how we're currently testing the [`devcontainers` org templates in CI](https://github.com/devcontainers/templates/blob/main/.github/workflows/test-pr.yaml).

**Comment by minasouliman** [comment]
Thanks so much @joshspicer, that perfectly answered my questions. I'll take a look at the `devcontainer templates apply` cli command and see if we can make that work in the meantime with some sort of options file maybe. Having this in VSCode is the most ideal scenario since that's what the whole team is using and providing a gui-based option of using a template with options will hopefully reduce the barrier to entry for those that don't want to mess around too much with cli commands but still want the benefits of devcontainers. I'll go ahead and add a comment on that discussion :)

And thank you as well for the PR for ACR credential!

You guys are doing awesome work btw!
