### ISSUE TITLE
[finalization] Declarative secrets

### ISSUE THREAD

**Issue by bdmac** [devcontainers/spec#216]
For discussion of the [declarative secrets specification](https://github.com/devcontainers/spec/blob/main/proposals/declarative-secrets.md).

This continues discussion found in the [original proposal](https://github.com/devcontainers/spec/issues/198).

**Comment by bamurtaugh** [comment]
The spec work is done here, so closing this issue!

Now various supporting tools can add their implementation, such as https://github.com/microsoft/vscode-remote-release/issues/8559 for the Dev Containers extension in VS Code.
