### ISSUE TITLE
Template team feedback #35867

### ISSUE THREAD

**Issue by bnhassin** [devcontainers/spec#258]
name: Backport PR to branch
on:
  issue_comment:
    types: [created]
  schedule:
    # once a day at 13:00 UTC to cleanup old runs
    - cron: '0 13 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  backport:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@main

**Comment by bnhassin** [comment]
![Screenshot_20230619-050558.png](https://github.com/devcontainers/spec/assets/1473765/4a0581e7-f93f-4b28-83dc-61b9bef4586b)

@bnhassin commented on #258 https://github.com/devcontainers/spec/issues/258

**Comment by bamurtaugh** [comment]
If you have a spec-specific request or bug, please feel free to file a new issue. Thank you!
