### ISSUE TITLE
Link to VS Code implementation of dev container schema leads to non-existent file

### ISSUE THREAD

**Issue by thevedicdeveloper** [devcontainers/spec#265]
Hello,

I was reading the documentation and came across a sentence that says 

![image](https://github.com/devcontainers/spec/assets/97366282/7f344404-21ea-4066-bef2-93ea29828dfc)

I was able to open the link provided in the word "here" as a hyperlink, but it leads to a non-existent file.

link to the documentation: https://containers.dev/implementors/json_reference/#schema

**Comment by thevedicdeveloper** [comment]
I would love to update the documentation if anyone can provide the link to that page.

**Comment by bamurtaugh** [comment]
Thank you @thevedicdeveloper! I believe the spec side of this is covered by https://github.com/devcontainers/spec/pull/257 which should be merged in soon.

If you're able to open a PR to update the containers.dev repo here, that'd be a fantastic help: https://github.com/devcontainers/devcontainers.github.io.

**Comment by thevedicdeveloper** [comment]
Thank you @bamurtaugh,

Sure I will open a PR to update the container.dev repo.
