### ISSUE TITLE
Ability to define user specific customizations.vscode.extensions

### ISSUE THREAD

**Issue by rickyjames35** [devcontainers/spec#295]
The ability to automatically install VS Code extensions into a devcontainer using customizations.vscode.extensions offers great convenience. However, when collaborating within a team, it's advisable to limit the installation to only those extensions that are essential for the project. For instance, consider `ms-vscode.cpptools-extension-pack` and `ms-vscode.cmake-tools`.

The question arises whether it's wise to automatically install even the essential VS Code extensions into a devcontainer, as the recommended approach is to maintain devcontainers in an IDE-agnostic manner. This, of course, leads to a separate discussion.

Nonetheless, many developers have specific extensions they prefer, such as Rainbow Indent and Github Copilot. With devcontainers, there's a need to reinstall these extensions each time the container is rebuilt. One method attempted involves volume mounting `/home/remoteUser/.vscode-server`. However, this approach presents permission issues and potentially other challenges.

Are there established best practices for effectively managing this situation?

**Comment by rickyjames35** [comment]
Related issues
- https://github.com/microsoft/vscode-remote-release/issues/8430
- https://github.com/devcontainers/spec/issues/22

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for opening the issue! 

> However, when collaborating within a team, it's advisable to limit the installation to only those extensions that are essential for the project. For instance, consider ms-vscode.cpptools-extension-pack and ms-vscode.cmake-tools.

@rickyjames35  Are you looking for a mechanism to opt out of extensions which gets added to the dev container (either by an image or Features)? Wondering if https://github.com/devcontainers/features/issues/386 could be helpful in your case.

> Nonetheless, many developers have specific extensions they prefer, such as Rainbow Indent and Github Copilot. With devcontainers, there's a need to reinstall these extensions each time the container is rebuilt. One method attempted involves volume mounting /home/remoteUser/.vscode-server. However, this approach presents permission issues and potentially other challenges.

How about using VS Code Settings sync? See https://code.visualstudio.com/docs/editor/settings-sync, however, in this case it needs to set per user account. Hence, I believe https://github.com/devcontainers/spec/issues/22 might be more appropriate in your case.

**Comment by bamurtaugh** [comment]
Settings Sync should bring your extensions to new devices! Please let us know if that's not what you're observing.

**Comment by rickyjames35** [comment]
Actually this is what I was looking for thanks
https://code.visualstudio.com/docs/devcontainers/containers#_always-installed-extensions
