### ISSUE TITLE
how to resolve other issues

### ISSUE THREAD

**Issue by phuquoc81** [devcontainers/spec#318]
if someone create the new way of coding and it work on and coding languages mobile phone or hand device

**Comment by bamurtaugh** [comment]
Hi there, if you have an issue specific to dev containers, please just let us know. Thank you!

**Comment by NaseHolmes** [comment]
money i need to send to my bank account and print. without print i going to have problem.

**Comment by TateGunning** [comment]
Hi @bamurtaugh Brigit,
The way your name is spelt "git" is a perfect fit for this application lol hope you are well. Yes I have a question, can dev containers be developed by other parties, as example, and automatically be pushed to subject without subject being made aware?

**Comment by NaseHolmes** [comment]
where are u from?
