### ISSUE TITLE
Where spec?

### ISSUE THREAD

**Issue by Luc45** [devcontainers/spec#32]
Hello!

I've read the README.md and I couldn't find a link to the actual spec. Is the specification already visible to the public?

If so, would it be possible to add a link to the spec in the README.md?

<img src="https://user-images.githubusercontent.com/9341686/169543787-e34cda98-546e-4d4e-98e5-ad58efb86897.png" width=300 height=170/>

**Comment by bamurtaugh** [comment]
Thanks for opening @Luc45! 

While we have released the [dev container CLI](https://github.com/devcontainers/cli), the more detailed specification is still under active development and has not yet been published. I've opened a PR to make this status more explicit in the [CLI blog post](https://github.com/microsoft/vscode-docs/pull/5361), and we also have https://containers.dev/ with information about this effort.

We'll be sure to let everyone know when the spec is available! And we appreciate you checking out the repo and providing this feedback.

If you have any other questions or feedback, please let us know!

**Comment by blmitrov** [comment]
[MiCA-Whitepaper-Pi-1.pdf](https://github.com/user-attachments/files/31400266/MiCA-Whitepaper-Pi-1.pdf)
[README.md](https://github.com/user-attachments/files/31400265/README.md)#
Blockchain #  
GDKL2WSKTCT3MGQ32AYHZP4JTFLUBLUUEZOEALCCMQW2PZCE2UZDS2FQpi
