### ISSUE TITLE
What state are the proposals in?

### ISSUE THREAD

**Issue by svenefftinge** [devcontainers/spec#338]
Reading through the proposal folder I couldn't tell if a proposal was implemented, rejected, considered.
It seemed like many of them were already implemented.
Can we add some metadata to the proposals? Or am I missing something?

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for the wonderful question! 

We do have [guidelines](https://containers.dev/implementors/contributing/#contribution-approaches) on contributing to the spec, as well as `labels` (`proposal` and `finalization`) defined for this process for GitHub Issues. See https://containers.dev/implementors/contributing/#review-process.

We add any proposal to the `proposals` folder, only if the proposal is accepted. It stays in that folder until the implementation is in progress. Once code/schema changes are released, I think we should move it out of the `proposals` folder.

@bamurtaugh Should we move some proposals (eg. https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-id-variable.md) out of the `proposals` folder as the code changes are implemented? I can see how it could be confusing for folks.

**Comment by bamurtaugh** [comment]
Thanks for opening @svenefftinge and for looping me in @samruddhikhandale! This is a great discussion.

> Should we move some proposals (eg. https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-id-variable.md) out of the proposals folder as the code changes are implemented? I can see how it could be confusing for folks.

This makes sense to me. I can open an initial PR to do this, and then also evaluate what needs to be added to containers.dev too.

**Comment by bamurtaugh** [comment]
I've opened https://github.com/devcontainers/spec/pull/339!
