### ISSUE TITLE
How to find out installed features or regenerate devcontainers.json for an existing container?

### ISSUE THREAD

**Issue by aaronshenhao** [devcontainers/spec#352]
I'm new to dev containers. I followed a YouTube tutorial several months back and created an Ubuntu container using VSCode, with several [features](https://containers.dev/features) selected. I've since lost the `devcontainers.json` file. Is there any way to regenerate it, or at least figure out what features were installed for that container?

**Comment by eljog** [comment]
Unfortunately it is not possible to regenerate a devcontainer.json file from a container.
As a general practice it is always advisable to check in all your devcontainer configurations in your source control system.
