### ISSUE TITLE
Syntax error in devcontainer feature JSON schema

### ISSUE THREAD

**Issue by jpillor-macquarie** [devcontainers/spec#356]
```
        "dependsOn": {
          "description": "An object of Feature dependencies that must be satisified before this Feature is installed. Elements follow the same semantics of the features object in devcontainer.json",
          "additionalProperties": true
          "type": "object"
        },
```

missing a comma here https://github.com/devcontainers/spec/blob/main/schemas/devContainerFeature.schema.json#L60

@joshspicer

**Comment by eljog** [comment]
Thank you for reporting.
I have a PR out for this (since it is vacation time, I don't expect it to get reviews/approval any soon)

Alternatively, if you wan't to contribute as PR now, I can help to approve and checkin that.

**Comment by jpillor-macquarie** [comment]
Thanks!🙏

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
