### ISSUE TITLE
Hackers 

### ISSUE THREAD

**Issue by 113ll3** [devcontainers/spec#403]
![Screenshot_20240122-185702.png](https://github.com/devcontainers/spec/assets/152741572/235d2a6b-5120-4d33-824a-f98b12f6090e)

**Comment by 113ll3** [comment]
This is on Google's feedback link and this is a screenshot of my device from Google's feedback IAM a consumer and I am not in a project or business help me

**Comment by bamurtaugh** [comment]
Hey there @113ll3, looks like this may not be the repo you're looking for as this isn't a dev container related repo. If you do have a dev container related issue, please let us know. Thank you!
