### ISSUE TITLE
Reference icon for devcontainers

### ISSUE THREAD

**Issue by felipecrs** [devcontainers/spec#42]
I'm writing a custom segment for my ZSH prompt, so I can easily tell whether I'm inside of a devcontainer or not. Refs https://github.com/romkatv/powerlevel10k/issues/1895. For now, it looks something like:

![image](https://user-images.githubusercontent.com/29582865/173197663-313cd7a7-92d0-4447-841f-e9de10f5bcc4.png)

But it could be improved, if there was a real "devcontainer" icon (and thereafter submitted to [Nerd Fonts](https://www.nerdfonts.com/)), so I could save space in my prompt by not having to print `devcontainer` after the icon/glyph (as an "arrow down box" is a too generic icon).

Of course, that would not be the only appliance, after all, https://containers.dev is still missing a favicon. 😋

**Comment by felipecrs** [comment]
Oh, nice! If you know the creator/or you have the sources, would you mind publishing an SVG variant of it?

**Comment by holytshirt** [comment]
Sorry can't help I'm not involved with the project I was just browsing 😄

**Comment by felipecrs** [comment]
@holytshirt oh, got it. Thank you for providing this input anyway!

**Comment by Chuxel** [comment]
Cool! I am a powerline10k fan myself.

@bamurtaugh - Can we get the SVG asset for the devcontainers org image from @misolori? We could put that and a png under `images` here maybe?

**Comment by misolori** [comment]
I pulled that icon from the Fluent icon library, which is open-sourced https://github.com/microsoft/fluentui-system-icons/blob/master/assets/Cube/SVG/ic_fluent_cube_32_filled.svg

**Comment by bamurtaugh** [comment]
Thanks for linking that, @misolori!

Since it's part of the open source Fluent icon library, I could add a reference link in the readme, rather than copying and uploading the image itself, if that sounds reasonable?

**Comment by bamurtaugh** [comment]
I opened https://github.com/devcontainers/spec/pull/49 to achieve the above readme note. Welcome any feedback!
