### ISSUE TITLE
Warn users using Docker Desktop on Linux

### ISSUE THREAD

**Issue by zmarffy** [devcontainers/spec#443]
This is more of a Docker Desktop on Linux issue, but wanted to mention it here because I feel like maybe VS Code should issue a warning about it? Even repos to test dev containers like [vscode-remote-try-node](https://github.com/microsoft/vscode-remote-try-node) will not work, as Docker Desktop on Linux has [an interesting file sharing conundrum](https://docs.docker.com/desktop/faqs/linuxfaqs/#how-do-i-enable-file-sharing). A workaround of setting `containerUser` and/or `remoteUser` as `root` might not be a great idea. Maybe if VS Code detects that a Linux user is using Docker Desktop, it should warn about this, proposing some actions to take.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for pointing us the issue. Can you open an issue in https://github.com/microsoft/vscode-remote-release/issues? The VS Code team should be able to help you provide guidance. Thanks! 

The `devcontainers` team does not maintain the VS Code UX or the `Dev containers` extension.

**Comment by zmarffy** [comment]
Done. https://github.com/microsoft/vscode-remote-release/issues/9643
