### ISSUE TITLE
`entrypoint` missing from schema

### ISSUE THREAD

**Issue by mingxiao** [devcontainers/spec#444]
According to the [merge logic](https://containers.dev/implementors/spec/#merge-logic), there should be an `entrypoint` parameter.

However, the `entrypoint` parameter is missing from the base [schema](https://github.com/devcontainers/spec/blob/main/schemas/devContainer.base.schema.json)

**Comment by samruddhikhandale** [comment]
The `entrypoint` property is only valid for Features, hence, you can find it [here](https://github.com/devcontainers/spec/blob/main/schemas/devContainerFeature.schema.json#L46).

![Image](https://github.com/devcontainers/spec/assets/24955913/329b790b-c2a2-44ea-96f6-b109a76262fb)

From ^, looks like there was a confusions as there is no ✔ for the `entrypoint` row under `devcontainer.json`. Hence, it does not exist for `devcontainer.json`

Feel free to reopen if you have any other doubts.

// cc @bamurtaugh I wonder if we should update the website with a note on `✓` and how to read the table.
