### ISSUE TITLE
@adamjstewart  We are aware about this and we will have a fix

### ISSUE THREAD

**Issue by AZOLOOK** [devcontainers/spec#470]
@adamjstewart  We are aware about this and we will have a fix

_Originally posted by @DragosDanielBoia in https://github.com/microsoft/ContributorLicenseAgreement/issues/167#issuecomment-2079431506_

_Originally posted by @AZOLOOK in https://github.com/Rashadoooz/demo-repository/issues/1_

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
