### ISSUE TITLE
<!-- Add a reference link (if necessary) !--->

### ISSUE THREAD

**Issue by AZOLOOK** [devcontainers/spec#471]
Depends on [add a reference link here]

- [x] Create a release (if necessary - which ensures images are up to date before deprecating )
- [x] Open a PR 
- [x] Update [templates](https://github.com/devcontainers/templates) (if necessary)
- [x] Update https://github.com/devcontainers/images/issues/90
- [x] Update [Microsoft Artifact Registry](https://mcr.microsoft.com/en-us/catalog?search=dev%20container) docs

_Originally posted by @AZOLOOK in https://github.com/devcontainers/images/issues/1093_

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
