### ISSUE TITLE
Observing yourself and @samruddhikhandale teach us this process has been fun. Thank you for allowing a learn and for adding read me color and more order as needed and greatly appreciated. The VS seems cool I am also curious about the spec proposals in container but with respect to the VS remote implantation. Offline. Is the tunnel a VS control, a user VPN on machine, or separate funnel altogether? A very interesting process nonetheless thanks.

### ISSUE THREAD

**Issue by Arya12-glitch** [devcontainers/spec#474]
Observing yourself and @samruddhikhandale teach us this process has been fun. Thank you for allowing a learn and for adding read me color and more order as needed and greatly appreciated. The VS seems cool I am also curious about the spec proposals in container but with respect to the VS remote implantation. Offline. Is the tunnel a VS control, a user VPN on machine, or separate funnel altogether? A very interesting process nonetheless thanks.

_Originally posted by @TateGunning in https://github.com/devcontainers/spec/issues/31#issuecomment-1895229242_

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
