### ISSUE TITLE
 postCreateCommand failed with exit code 127. Skipping any further user-provided commands.

### ISSUE THREAD

**Issue by TAM360** [devcontainers/spec#482]
Hi everyone, 

I am facing some issues while creating a dev-container for Kubebuilder repository. I've created the following `.devcontainer.json' file:

```json
{
  "name": "Kubebuilder DevContainer",
  "build": {
    "dockerfile": "./Dockerfile",
    "context": "."
  },

  "features": {
    "ghcr.io/devcontainers/features/docker-in-docker:2.11.0": {
      "moby": true,
      "azureDnsAutoDetection": true,
      "version": "latest"
    },
    "ghcr.io/devcontainers/features/common-utils:2": {
      "installZsh": false,
      "upgradePackages": true,
      "username": "devcontainer",
      "userUid": "1001",
      "userGid": "1001"
    },
    "ghcr.io/devcontainers/features/git:1": {
      "ppa": true,
      "version": "system"
    },
    "ghcr.io/devcontainers/features/go:1": {
      "version": "1.22.5"
    }
  },

  "runArgs": ["--privileged"],
  // "forwardPorts": [],

  // Use 'postCreateCommand' to run commands after the container is created.
  // "postCreateCommand": [
  //   "make install",
  //   "go version",
  //   "kind create cluster",
  //   "kubectl version",
  //   "kubectl get nodes"
  // ],

  "postCreateCommand": "./post-install.sh"

  // "postStartCommand": [
  //   "go version",
  //   "kubectl version --client",
  //   "kind version"
  // ]

  // Configure tool-specific properties.
  // "customizations": {},

  // Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
  // "remoteUser": "root"
}

```

```Dockerfile
buster, 1.19-buster, 1.18-buster
ARG TAG=1.23rc2-bullseye
FROM golang:${TAG}

# Install dependencies
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64 && \
    chmod +x ./kind && \
    mv ./kind /usr/local/bin/kind

COPY post-install.sh .

RUN chmod +x post-install.sh
```

The issue is that the `postCreateCommand` isn't able to find the `post-install.sh` shell script, even if I add it in my `Dockerfile`

```bash
bin/sh: 1: ./post-install.sh: not found
[48894 ms] postCreateCommand failed with exit code 127. Skipping any further user-provided commands.
Error: Command failed: /bin/sh -c ./post-install.sh
    at N7 (/home/linuxbrew/.linuxbrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:235:130)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
If I pass the iniline command to `postStartCommand`, I get errors related with not being able to find the Golang binary, even though it exists as part of parent.

```bash
Container started
Not setting dockerd DNS manually.
Running the postCreateCommand from devcontainer.json...

OCI runtime exec failed: exec failed: unable to start container process: exec: "go version": executable file not found in $PATH: unknown
[1664464 ms] postStartCommand failed with exit code 126. Skipping any further user-provided commands.
Error: Command failed: go version kubectl version --client kind version
    at N7 (/home/linuxbrew/.linuxbrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:235:130)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Can someone provide any hint as to what am I doing wrong exactly?

**Comment by samruddhikhandale** [comment]
The issues you're encountering are likely due to the context in which the `postCreateCommand` and `postStartCommand` are executed. Here are a few steps to troubleshoot and resolve these issues:

1. Ensure post-install.sh is in the correct location: Make sure that post-install.sh is in the root of your context directory (where your .devcontainer.json is located) so that it gets copied correctly into the Docker image.
2. Verify the file permissions and path: Ensure that the post-install.sh script has the correct permissions and is located in the expected directory inside the container.
3. Check the PATH environment variable: Ensure that the PATH environment variable includes the directory where Go and other binaries are installed.

**Comment by TAM360** [comment]
@samruddhikhandale  `post-install.sh` script is present in `.devcontainer` (https://github.com/TAM360/kubebuilder/tree/master/.devcontainer) folder already. I even added the same script as part of my `Dockerfile` as well, as you can see here (https://github.com/TAM360/kubebuilder/blob/dd28e8b7924186615713faa5c03256e73c3f9aaf/.devcontainer/Dockerfile#L13).

**Comment by TAM360** [comment]
Update: I was able to resolve the issue. I listed the contents of my dev-container using `ls -altr` and it turned out that the default directory  was the Kubebuilder (my repository) itself in which `.devcontainer`  sub-directory was present.
In my `postCreateCommand` field, I had wrongly mentioned `./post-install.sh` when in fact it should had been `./.devcontainer/post-install.sh`

**Comment by TAM360** [comment]
Update: I was able to resolve the issue. I listed the contents of my dev-container using `ls -altr` and it turned out that the default directory was the Kubebuilder (my repository) itself in which `.devcontainer` sub-directory was present.
In my `postCreateCommand` field, I had wrongly mentioned `./post-install.sh` when in fact it should had been `./.devcontainer/post-install.sh`.
