### ISSUE TITLE
Issue with Creating Remote Containers Using Dev Containers 242 in IDEA 24.2

### ISSUE THREAD

**Issue by 9mlcy7** [devcontainers/spec#488]
In IDEA 24.1 (dev containers 241), you could connect from a local environment (Windows) to a remote server (Linux) Docker instance and successfully build a remote container by selecting the local devcontainer.json file.

However, in IDEA 24.2 (dev containers 242), after connecting from a local environment (Windows) to a remote server (Linux) Docker instance, you can only select the remote devcontainer.json file and encounter the following error:

Worker binary deploy failed: Worker binary deploy failed: check command log for details: com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "docker.exe": CreateProcess error=2, The system cannot find the file specified.

![image](https://github.com/user-attachments/assets/31ac4e7d-684a-4534-8160-a51ef17cf98a)

`Ideally, IDEA should be able to build directly using the remote Docker server without requiring Docker to be installed locally. Is this a bug or is it by design? Why does this issue not occur in version 24.1?`

Here is my devcontainer.json configuration file:

```
{
	"name": "Remote Dev",
	"workspaceMount": "source=/remote-dev/test,target=/workspaces,type=bind",
	"workspaceFolder": "/workspaces",
	"image": "demo/remote-dev:latest",
	"runArgs": [
		"--cap-add=SYS_PTRACE",
		"--security-opt",
		"seccomp=unconfined"
	],
	"remoteUser": "root"
}
```

**Comment by chrmarti** [comment]
The problem you report seems to be specific to IDEA. When connecting to a SSH server using the Dev Containers extension for VS Code, the extension runs the Dev Container CLI on the SSH server and doesn't require the Docker CLI on the local machine.
