### ISSUE TITLE
Vysoká škola 

### ISSUE THREAD

**Issue by Vaneska1401** [devcontainers/spec#492]
[Informationen zu Entwicklungscontainern](https://docs.github.com/de/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers#about-dev-containers)

**Comment by Vaneska1401** [comment]
https://docs.github.com/de/get-started/start-your-journey

**Comment by Vaneska1401** [comment]
cervenakovav12@gmail.com

**Comment by Vaneska1401** [comment]
cervenakovav12@gmail.com

**Comment by bamurtaugh** [comment]
Seems this might've been opened on accident, please let us know if you do have a dev container issue. Thanks!
