### ISSUE TITLE
Changing font is not working

### ISSUE THREAD

**Issue by h4rvey-g** [devcontainers/spec#497]
Hi! I'm using devcontainer on a remote linux server. And I have installed Nerd Font on both my local pc and inside the container. I tried to set it as the editor font in the user settings.json
```json
"editor.fontFamily": "MonaspiceAr NF"
```
Now this works when I open files on my local pc, or on the remote linux server, but not in the devcontainer. It seems that only these default fonts are available in the container: Consolas, 'Courier New', monospace, despite I have installed Nerd Fonts inside the container.
```bash
vscode ➜ ~ $ fc-list | grep "MonaspiceAr"
/home/vscode/.local/share/fonts/MonaspiceArNerdFont-Bold.otf: MonaspiceAr Nerd Font,MonaspiceAr NF:style=Bold
/home/vscode/.local/share/fonts/Monaspace/MonaspiceArNerdFontMono-Regular.otf: MonaspiceAr Nerd Font Mono,MonaspiceAr NFM:style=Regular
/home/vscode/.local/share/fonts/Monaspace/MonaspiceArNerdFont-BoldItalic.otf: MonaspiceAr Nerd Font,MonaspiceAr NF:style=Bold Italic
/home/vscode/.local/share/fonts/Monaspace/MonaspiceArNerdFontPropo-LightItalic.otf: MonaspiceAr Nerd Font Propo,MonaspiceAr NFP,MonaspiceAr NFP Light:style=Light Italic,Italic
/home/vscode/.local/share/fonts/Monaspace/MonaspiceArNerdFontMono-Bold.otf: MonaspiceAr Nerd Font Mono,MonaspiceAr NFM:style=Bold
...
```
Any ideas?

**Comment by h4rvey-g** [comment]
Worked after reloading window.

**Comment by 301166** [comment]
I dont have idea.
