### ISSUE TITLE
Hi @luftuq,

### ISSUE THREAD

**Issue by Xcopz1** [devcontainers/spec#507]
#506               Hi @luftuq,
Thank you for reporting this issue. To help us understand and resolve it more efficiently, could you please provide a minimal reproduction example? This will allow us to replicate the problem on our end and investigate it further.

_Originally posted by @gauravsaini04 in https://github.com/devcontainers/spec/issues/476#issuecomment-2404435859_

**Comment by bamurtaugh** [comment]
Looks like this may not have the actionable info mentioned in the original comment. If you have that info, or a specific issue related to dev containers, please let us know. Thank you!
