### ISSUE TITLE
Fall back to build from Dockerfile when image not downloadable

### ISSUE THREAD

**Issue by MartinLoeper** [devcontainers/spec#526]
Is it possible with the current spec to configure that the devcontainer should be built from given Dockerfile if the specified image cannot be pulled?

As far as I understand, the "build" and "image" properties are mutually exclusive, i.e. the devcontainer is either "Image based" or "Dockerfile based" to say it in the words of the [spec](https://containers.dev/implementors/spec/#image-based).

My usecase is to provide an escape hatch for unreliable internal docker registries. I want developers to be able to build their local devcontainers on their own machines in case the company's docker registry is unreachable for some reason.

**Comment by chrmarti** [comment]
These cannot be combined in the same devcontainer.json currently. You could use 2 devcontainer.json though: One to build the image in CI and to fall back to locally when the registry isn't available and one referring to the image. The UIs will offer to pick from the two when the second is in a subfolder of `.devcontainer`, e.g.: `.devcontainer/devcontainer.json` and `.devcontainer/build/devcontainer.json`.

For a GitHub action for CI see: https://github.com/devcontainers/ci

**Comment by MartinLoeper** [comment]
I can confirm this totally works. It would be nice to extend one devcontainer.json file with the other one, but thats just a nitpick.
