### ISSUE TITLE
"extensions" property not documented

### ISSUE THREAD

**Issue by bnb** [devcontainers/spec#55]
I am currently trying to build a devcontainer to test a GitHub feature (fingers crossed), and want to specifically install extensions. Unfortunately, it does not seem like the `extensions` property - which is even used [in this org](https://github.com/devcontainers/ci/blob/main/.devcontainer/devcontainer.json#L27-L35) - is documented in the specification.

Is this expected, since devcontainers are theoretically agnostic of the editor? Or is this documentation just missing?

**Comment by Chuxel** [comment]
This is covered under "tool specific properties."  The original `extensions` property was recently moved under `customizations`(see #1) but the old location is still there for backwards compatibility.

https://containers.dev/supporting#visual-studio-code

**Comment by bnb** [comment]
Yeah, it's a bit strange but it works well enough.
