### ISSUE TITLE
[finalization] dev container feature distribution specification

### ISSUE THREAD

**Issue by joshspicer** [devcontainers/spec#70]
A forum to discuss the [dev container feature distribution specification](https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features-distribution.md).

A continuation of the discussion found here: https://github.com/devcontainers/spec/issues/7

**Comment by guiyomh** [comment]
Whaou! I love ❤️ this new file organization. I was able to create and test [my own features](https://github.com/guiyomh/features) quickly.
Good work 👍

**Comment by muruku1** [comment]
Once again me you guys 😀

**Comment by 8Viktor-1** [comment]
> A forum to discuss the [dev container feature distribution specification](https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features-distribution.md).
> 
> A continuation of the discussion found here: [#7](https://github.com/devcontainers/spec/issues/7)

**Comment by thanujakat-oss** [comment]
Good
