### ISSUE TITLE
Publish reference implementation

### ISSUE THREAD

**Issue by chrmarti** [devcontainers/spec#9]
We want to extract a reference implementation for the dev container spec from our existing implementation. The current proposal is to make a CLI available that can take a devcontainer.json and create and configure a dev container from it.

Splitting it into 2 stages at first:
```
devcontainer up --workspace-folder .
devcontainer run-user-commands --workspace-folder .
```
`up` could be split into `build` and `run` to make building the image available separately.
`run-user-commands` runs `"postCreateCommand"` and other user-provided commands.

Products might choose to add to the container's setup between the two commands (e.g., Remote-Containers starts the ssh-agent forwarding among other things).

/cc @joshspicer @Chuxel @2percentsilk @bamurtaugh

**Comment by bamurtaugh** [comment]
Thanks for opening this!

> up could be split into build and run to make building the image available separately.

I like this as it feels like it allows for easier iteration on the dev container.

**Comment by chrmarti** [comment]
There might be two stories to tell here: One is about the reference implementation that can be used to build products like Codespaces and Remote-Containers and one is about a CLI that can be used in CI.

We could add a `run` command to run one-off commands (like an interactive shell) in a temporary container.

**Comment by chrmarti** [comment]
Adding an `exec` command for now. I suggest we add more commands once we have some initial feedback on what we currently have.

**Comment by bamurtaugh** [comment]
The reference implementation is now available at https://github.com/devcontainers/cli!

Closing this issue as the CLI repo is published, but please let me know if there's more we should discuss here. Thanks!
