### ISSUE TITLE
Proposal: Initial files to display

### ISSUE THREAD

**Issue by joshaber** [devcontainers/spec#97]
**Problem:** We want customers to be able to configure which files are automatically opened by attaching clients. This is to support both education scenarios and collaboration/getting started scenarios.

**Proposal:** We add the `initialDisplayFiles` top level `array` property, listing the paths to open, relative to the workspace folder. These files would only be opened the first time the client attaches.

```jsonc
"initialDisplayFiles": [
  "file-a.txt",
  "file-b.txt"
]
```

Client-specific customizations can then be applied using `customizations`, keying off the file path, e.g.:

```jsonc
"customizations": {
  "vscode": {
    "initialDisplayFiles": {
      "file-a.txt": {
        // VS Code specific properties
      }
    }
  }
}
```

**Comment by edgonmsft** [comment]
I like this idea but not sure if this would only apply on first open, or if the files should be open always even if the editor remembers the last files opened.

**Comment by bamurtaugh** [comment]
I like this idea too! Wondering what kind of customizations you're envisioning a tool would apply to a file?

**Comment by joshaber** [comment]
> not sure if this would only apply on first open, or if the files should be open always even if the editor remembers the last files opened.

Good question! I propose they only apply the first time the client attaches. Past that if the user closes the files that's their prerogative.

I updated the proposal above to specify that 👍 

>Wondering what kind of customizations you're envisioning a tool would apply to a file?

For VS Code I'm imagining properties like `viewColumn`, `selection`, or `preview`. So essentially [`TextDocumentShowOptions`](https://code.visualstudio.com/api/references/vscode-api#TextDocumentShowOptions) 😄

**Comment by chrmarti** [comment]
Is this something a VS Code extension could implement? The extension would be listed in the devcontainer.json for installation and it would have a setting listing the files to open also in the devcontainer.json.

**Comment by joshaber** [comment]
> Is this something a VS Code extension could implement? The extension would be listed in the devcontainer.json for installation and it would have a setting listing the files to open also in the devcontainer.json.

That'd work for VS Code but then the question becomes: what about other clients? Do I need to duplicate the list for JetBrains? What about other clients I don't even know about?

**Comment by Chuxel** [comment]
>> not sure if this would only apply on first open, or if the files should be open always even if the editor remembers the last files opened.
>
> Good question! I propose they only apply the first time the client attaches. Past that if the user closes the files that's their prerogative.
>
> I updated the proposal above to specify that 👍

@edgonmsft @joshaber Yeah it would be really annoying if it did it every time the client connected. The experiences with continual welcome screens really makes me question even first run experiences that are as forceful as bringing up a tab... notifications are bad enough. If the user closed the tab, we should respect that.

>> Is this something a VS Code extension could implement? The extension would be listed in the devcontainer.json for installation and it would have a setting listing the files to open also in the devcontainer.json.
>
> That'd work for VS Code but then the question becomes: what about other clients? Do I need to duplicate the list for JetBrains? What about other clients I don't even know about?

@joshaber @chrmarti Each client would have to implement this, so I think the question is whether this scenario is important enough to say that all clients that implement the dev container spec should support it to be "compliant." The "customizations" section is more for things that are optional for a given client to support. For example, would we require a JetBrains extension exist to do this for those tools? Unlike most top-level properties, a CLI can't implement this one.

Put another way - what do we want to signal to implementors?

Right now, we have some disconnects between Remote - Containers and Codespaces  support on top level properties and it causes lots of issues and confusion.

**Comment by joshaber** [comment]
Thanks @Chuxel, those are good considerations.

I wonder if the question is really: does "initial files" makes sense as a _dev containers_ feature or only as a _Codespaces_ feature?

The expectations of a Codespaces user of Codespaces clients may differ from those of dev containers users & clients. "Initial files" may be a sufficiently important feature for Codespaces that we expect Codespaces clients to implement it but not so for remote containers.

Another potential angle: the spec should be conservative. If Codespaces' implementation of "initial files" proves sufficiently useful & popular then remote containers may hear requests for support.

**Comment by Chuxel** [comment]
> Thanks @Chuxel, those are good considerations.
> 
> I wonder if the question is really: does "initial files" makes sense as a _dev containers_ feature or only as a _Codespaces_ feature?
> 
> The expectations of a Codespaces user of Codespaces clients may differ from those of dev containers users & clients. "Initial files" may be a sufficiently important feature for Codespaces that we expect Codespaces clients to implement it but not so for remote containers.

@joshaber Yeah, if your mental model is that for Codespaces, non-VS Code clients would be modified/extended to support this, then I think it is worth discussing whether that should be a general rule.  Remote - Containers is VS Code only, so that's N/A here.  What I am getting at is whether this is really going to end up being implemented as a VS Code feature, or a multi-client feature since that has an affects the conversation here.
 
> Another potential angle: the spec should be conservative. If Codespaces' implementation of "initial files" proves sufficiently useful & popular then remote containers may hear requests for support.

Right, that was kind of what I was wondering as well - it's easy enough to move thing up to the top level over time but removing something once it's at the top level is hard since developers will depend on it.

We could leave this in proposed for now and have it as a `customizations.vscode` property to start, for example.

**Comment by chrmarti** [comment]
Note that VS Code has a setting for opening the README at startup that might already cover part of what we are trying to do here: 
<img width="631" alt="image" src="https://user-images.githubusercontent.com/9205389/191443795-3e1bff66-c2b3-4172-95b5-64c360a3ca38.png">

**Comment by Chuxel** [comment]
Good point - wonder if the right thing to do would be to PR microsoft/vscode to allow more paths.

**Comment by joshaber** [comment]
We've landed on putting this in `customizations.codespaces` since it's not clear this belongs in the spec and we want it to apply across Codespaces clients. I'll go ahead and close this, and we can revisit this if y'all hear requests for broader dev containers support.
